fullnameOverride: ingress-nginx-internal
controller:
  service:
    annotations:
      lbipam.cilium.io/ips: 172.16.0.86
    externalTrafficPolicy: Cluster
  ingressClassResource:
    name: internal
    default: true
    controllerValue: k8s.io/internal
  admissionWebhooks:
    objectSelector:
      matchExpressions:
        - key: ingress-class
          operator: In
          values:
            - internal
  config:
    allow-snippet-annotations: true
    annotations-risk-level: Critical
    # taken from https://github.com/ai-robots-txt/ai.robots.txt
    block-user-agents: AdsBot-Google,Amazonbot,anthropic-ai,Applebot-Extended,Bytespider,CCBot,ChatGPT-User,ClaudeBot,Claude-Web,cohere-ai,Diffbot,FacebookBot,FriendlyCrawler,Google-Extended,GoogleOther,GPTBot,img2dataset,omgili,omgilibot,peer39_crawler,peer39_crawler/1.0,PerplexityBot,YouBot,
    client-body-buffer-size: 100M
    client-body-timeout: 120
    client-header-timeout: 120
    enable-brotli: "true"
    enable-ocsp: "true"
    enable-real-ip: "true"
    force-ssl-redirect: "true"
    hide-headers: Server,X-Powered-By
    hsts-max-age: 31449600
    keep-alive-requests: 10000
    keep-alive: 120
    log-format-escape-json: "true"
    log-format-upstream: |
      {"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr", "x_forwarded_for": "$proxy_add_x_forwarded_for", "request_id": "$req_id", "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status": $status, "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri", "request_query": "$args", "request_length": $request_length, "duration": $request_time, "method": "$request_method", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent"}
    proxy-body-size: 0
    proxy-buffer-size: 16k
    ssl-protocols: TLSv1.3 TLSv1.2
    use-forwarded-headers: "true"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespaceSelector:
        any: true
  extraArgs:
    default-ssl-certificate: network/three14creations-com-staging-tls
  resources:
    requests:
      cpu: 100m
    limits:
      memory: 500Mi
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dzpk0zfneupvk2a8d0wu6n8n3deqkl2r7lpd7t3ln028zfcrqpgqv80w9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2clkzUnV2UDlOaVFLYnBQ
        bmkyM0k0dHRMZ01kN1dsNkpxd3ZwUFd1SVFzCjk5Rm5ZbHYzYlBqellMeG42RjJU
        MlFHaUo3cVFLdEVsM0Q1NkR1bWNYZmMKLS0tIFQ5SFozNGZidW1OeWxzaHpQTUo2
        c2l0Mk9QZjdVTEhKSXZUZW5hMTJuQWMKSpj9INYF9vb5Rk0Lq1cMDNXOxOF1VnVh
        LVAcPaUsIJp2UhYUpT6+tRPe5L6n0el/xXql6l2m+2RxmkAMSsc6cw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T05:01:00Z"
  mac: ENC[AES256_GCM,data:eYGUcLAhF/FCwpA2OzcEdYVkX58Qum0bnWaBm23i+vBu2f9NvPY1D7OkWmnKnTPECQgDZa8o2b6Y17NOJPvCP7e2XbDY7Cb8tmo49HxC8KZ4fJ28JUQw9yRzptIkShzQldMvfBqEnQy9h0LrWyJjyomk/pU6cAxJDFQSZkNdOJQ=,iv:HQ6z30cxuRvKbbP7f5NypykfCD8Ylrj47DLw3suxr7s=,tag:tU2F7VR38CaZTsotFpbT3w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
