fullnameOverride: external-dns
provider: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: external-dns-secret
        key: api-token
extraArgs:
  - --cloudflare-dns-records-per-page=1000
  - --cloudflare-proxied
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
  - --events
  - --ignore-ingress-tls-spec
  - --ingress-class=external
policy: sync
sources:
  - crd
  - ingress
txtPrefix: k8s.
txtOwnerId: default
domainFilters:
  - jw2.org
serviceMonitor:
  enabled: true
podAnnotations:
  secret.reloader.stakater.com/reload: external-dns-secret
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dzpk0zfneupvk2a8d0wu6n8n3deqkl2r7lpd7t3ln028zfcrqpgqv80w9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUmkycXBYTmFpbHNrNlJ5
        bXNxYjFPM3VVTlE2ZEdtL3VjdThtckxPcEEwClRXYSsxZHJmSG1tNkRrcDdkTXlt
        ZDdlUUIxK0I1VGVtOEVOWXh1UjNpL1kKLS0tIEtkbmFCMTNmMFEvUytadGxLMHcw
        Z3A4U1BwbEE4S2IzTDFsdmluQndhTlUK6bOJbjf6O1QvWiDKMRfdR3ucIyLNGrXM
        qFm/JhrkeodgIga5WHpfJR7leLGHa12R8VWd0FuFd5vHBgiazxJB7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T04:26:52Z"
  mac: ENC[AES256_GCM,data:CtEPnl2AvX7bqSgExk+kZ/k4uUXVNdGe3ZrkI8aobM0K9/YelQL30nAJJRmFZCGKsvZwP4EO3Ll9rGlM8MXoIBVDXWKMoBG+w1WLX3jaZqwdb00y7f5DFv8/eR+1Cn2lsJmWayR4S1zYZk/bTeP94Uinui+3fwCpVUIYvfz6Y4w=,iv:qABCC37AeNPBwIAI9mbGMf5TS7VCA0RlGZw1aGaFQ7w=,tag:HH3sz6s1rxm8zNB5mvsLfA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
