fullnameOverride: external-dns
provider: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: external-dns-secret
        key: api-token
extraArgs:
  - --cloudflare-dns-records-per-page=1000
  - --cloudflare-proxied
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
  - --events
  - --ignore-ingress-tls-spec
  - --ingress-class=external
policy: sync
sources:
  - crd
  - ingress
txtPrefix: k8s.
txtOwnerId: default
domainFilters:
  - three14creations.com
serviceMonitor:
  enabled: true
podAnnotations:
  secret.reloader.stakater.com/reload: external-dns-secret
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dzpk0zfneupvk2a8d0wu6n8n3deqkl2r7lpd7t3ln028zfcrqpgqv80w9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eWNPMHVlZkpJNVBhRjg2
        RGhHS3Y0NjZtTGFtOWVhYlVDUnpiS1N6c1VZClZEcE1wcGg5NWpxNGxyd2FYUG1B
        ek94dURGVVdkQU9aRlVFL2poRG82SkEKLS0tIG0wQWJXbEYrVkZ0UFRrVVZLNlpG
        NXVvUXlESlVwVWhoM3VlRkhGTWpwY1kK6WpW+6/oDa4BTUr2R+mzyGfvq2RjZge/
        /ZaUr01Oys72xB2T8w2tbsEt/gDeVry5fOy3vtIDflCvqEJjTmqBgg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T05:00:59Z"
  mac: ENC[AES256_GCM,data:xqYc7HbSQh8nLU1sOJqYK9LFTFv2W/NuwiVv6SKMQ8zvUJ3uj/9YZ5SfFNamFdhFgNJPGqutlsxzzOXW77HbR2wA4qMNRGAgAkGDECI5J1KF4B7/t+Wz5s4/zEcB/dsQ1WBUDJ4oqCB7DSlMlAd+XBidsQZfK44dHO4ETWSxruQ=,iv:OnPOacY1+ulhwrHT+U7t0zd/6+liMxmaKclmZprupog=,tag:I51+HwhDSugHPEJ9RlTf4A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
