# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - three14creations.com
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dzpk0zfneupvk2a8d0wu6n8n3deqkl2r7lpd7t3ln028zfcrqpgqv80w9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtV0RkS2NiNkR1OTlTcy9k
        V2hJODNuSEY4bkdmT2M5OE1mVVR4ZUlhb21FCi8zRDN6T0lrazhna3dyV1phdUIv
        cWQzTjBMQTN1bk9KV1RETk14dnlSMG8KLS0tIERuMGxNcWxVcWNyS0ZkSkxCWTZD
        RCtyZDhXbzFQSHpBclplMHdnK2xVQ1EKcon4PZvh9cwOLvJTn4lD02l9z8R+7xOJ
        t7Uyv+T7Zhn563GMKVPC4Vc5u8yCXrOY6MJNU6Al0FbTYkg1Iwl/UA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T05:00:59Z"
  mac: ENC[AES256_GCM,data:la1O0MDLziMQ2urKY2ef8iaEzqzUN2G1j5gZCDG+qY9lVfOeaeaSyo32GBCOfEtU8iPIjjQHwrnjpwfq7/vCCPszk+VRNCZtElpF5rg3hpzexnfB/0UdyjS4cFweNvkVwQdaR2GasijrKKYy/Tq7M+bWpFdm+bjAGuf2wyIgeaw=,iv:BBpkChj9PT3/54vZiUCLVQCuqUnOPo4RMcpAQjXRqAY=,tag:CjbMrhG7Z1MADqZOHMSJtw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - three14creations.com
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dzpk0zfneupvk2a8d0wu6n8n3deqkl2r7lpd7t3ln028zfcrqpgqv80w9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtV0RkS2NiNkR1OTlTcy9k
        V2hJODNuSEY4bkdmT2M5OE1mVVR4ZUlhb21FCi8zRDN6T0lrazhna3dyV1phdUIv
        cWQzTjBMQTN1bk9KV1RETk14dnlSMG8KLS0tIERuMGxNcWxVcWNyS0ZkSkxCWTZD
        RCtyZDhXbzFQSHpBclplMHdnK2xVQ1EKcon4PZvh9cwOLvJTn4lD02l9z8R+7xOJ
        t7Uyv+T7Zhn563GMKVPC4Vc5u8yCXrOY6MJNU6Al0FbTYkg1Iwl/UA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T05:00:59Z"
  mac: ENC[AES256_GCM,data:la1O0MDLziMQ2urKY2ef8iaEzqzUN2G1j5gZCDG+qY9lVfOeaeaSyo32GBCOfEtU8iPIjjQHwrnjpwfq7/vCCPszk+VRNCZtElpF5rg3hpzexnfB/0UdyjS4cFweNvkVwQdaR2GasijrKKYy/Tq7M+bWpFdm+bjAGuf2wyIgeaw=,iv:BBpkChj9PT3/54vZiUCLVQCuqUnOPo4RMcpAQjXRqAY=,tag:CjbMrhG7Z1MADqZOHMSJtw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
