# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - jw2.org
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dzpk0zfneupvk2a8d0wu6n8n3deqkl2r7lpd7t3ln028zfcrqpgqv80w9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWHBzZlp6RXl1SS9IRzJh
        Mm5KT2kyc3JVa1dEaDBYdG5Uayt2b01tWmpFCnNXdjVtSjZ3aWhVM2ZYcUhPT0No
        V3FCZzhlZzBsMkxxZkJUd0w3OUExRVkKLS0tIDhpM1R4dWJvcWhpSFRFcmJSQll3
        dUNFQ1dYVjJpTlNCZEVOakhlM0F1ZHMKuh/M1r0HhNmtQNvf5CleXRBx58735d/t
        0IvVx3ERTlGzgM6Ll8F0s11NboCPs/IYqQ8TAlq6QjjahgaQNQL2RQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T04:26:52Z"
  mac: ENC[AES256_GCM,data:ayXxFEl/em8KYfwrapzS3/A5y+aSfPoIbx3i7CJV/c1SIb/Y6QGecXmri7omFLCrmIsj/f0+i4WJG12rGR/HTdpeouQPNDaJ1BNkRVFkjmRDGL3PYy5Zz4wKhF8yD81bli57Sqhsf+d5sSukurua4uijjZKvbP5ZWZdwJ2xEpgM=,iv:CIlm9qO5/aatBBpiJYqH2TAzqMiMBoGbRTXfTbBWaWc=,tag:OzJfF+Kbpef/Wj+hxsnDig==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - jw2.org
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dzpk0zfneupvk2a8d0wu6n8n3deqkl2r7lpd7t3ln028zfcrqpgqv80w9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWHBzZlp6RXl1SS9IRzJh
        Mm5KT2kyc3JVa1dEaDBYdG5Uayt2b01tWmpFCnNXdjVtSjZ3aWhVM2ZYcUhPT0No
        V3FCZzhlZzBsMkxxZkJUd0w3OUExRVkKLS0tIDhpM1R4dWJvcWhpSFRFcmJSQll3
        dUNFQ1dYVjJpTlNCZEVOakhlM0F1ZHMKuh/M1r0HhNmtQNvf5CleXRBx58735d/t
        0IvVx3ERTlGzgM6Ll8F0s11NboCPs/IYqQ8TAlq6QjjahgaQNQL2RQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T04:26:52Z"
  mac: ENC[AES256_GCM,data:ayXxFEl/em8KYfwrapzS3/A5y+aSfPoIbx3i7CJV/c1SIb/Y6QGecXmri7omFLCrmIsj/f0+i4WJG12rGR/HTdpeouQPNDaJ1BNkRVFkjmRDGL3PYy5Zz4wKhF8yD81bli57Sqhsf+d5sSukurua4uijjZKvbP5ZWZdwJ2xEpgM=,iv:CIlm9qO5/aatBBpiJYqH2TAzqMiMBoGbRTXfTbBWaWc=,tag:OzJfF+Kbpef/Wj+hxsnDig==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
