# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:LQ/Hx4AZ8veskW1wqpGAtEjG7rwqpD2ZFkWPhM6/rKm8s86T245shA==,iv:hsKMBab5MMuJdgMNoP9BeD79FrD6s9/n4KppxMStoV4=,tag:x/xmImWjGfIiXb16b9Ppjg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dzpk0zfneupvk2a8d0wu6n8n3deqkl2r7lpd7t3ln028zfcrqpgqv80w9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVFUza25NellPeW9XamxW
        QVpnNkc4bllVVU4wNlBlb2NqbTNXa1E3VHhBCjQ1VlZRRHFJM2UxRUNpeVBTRkxO
        N2ZxbmNXdGhTcDJLTGRIRWJlbSt4bUkKLS0tIFByZnZRTnl3YlMxcFNQbTVZYVlP
        ZEpqenN5M1MvWVFIUVU2STVwV2N6V2cKn4A0pB+LzBM3ouVHJSL3i2nQlKDUaFzu
        p0oyp5C7UwCQgExd8MOXD8uFnvTvAqrdIgH5AlWf5xWiFHts9hn6jQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T05:00:59Z"
  mac: ENC[AES256_GCM,data:S1+nFRezpbJFHKZ1NO5P0vd6djrIeYSOAVpyjONWxwTb0LrguEjJZo86rJAIFj0vdCmBvwKl7TWUIuRxCQd/mA0siphj/lzZlWnUFn9EGYjPTg0k3qRf6Y1Qq1wtpFrGoFC3+faRVtfbc1fyatywIxKO9J1hsHbpAxpK1eUIu44=,iv:BbEmRlkWBXl97qOX5qMIVSLRgtgD6zOb4vKBNUMn3zI=,tag:VmYoEb/o5Ezlc2gvVtmX6w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
