# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:vHu1gJvrylThu6p9wJcL+9g5F8Mgb+h/Hb4yYZzJFa3fHvadNRE2Vg==,iv:fVEsp3yGwvEFtwofV+50z7SCgfaL/xsz7yXbjYmK1ek=,tag:GNX4QQmkDR/4YVxKBuZbSA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dzpk0zfneupvk2a8d0wu6n8n3deqkl2r7lpd7t3ln028zfcrqpgqv80w9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndVhzbzB5ZHRVTS9XdFVz
        WjJFU0poQ3hvU0Q0Zzg4WFFTOSs1dWNpSVZNCmN3cWdCc0R4RjZhQ21ockdseElB
        cmZIZUxFeThtUUFBbmNDUFpPaFNHWkkKLS0tIEtVMU5mbzBjV3JNQzZYMWNWbC9p
        OGpoYXE2N0JJL2lOTm9vdm1KWWpuSHcKp14mZsdt0hO3Ic85qzG8axY2yO/Lmev6
        i+C0SIad70OmOKc2TRRfUttkI0dP5FvPkyU+4lX1jXWzAGCpslzrxQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T04:26:52Z"
  mac: ENC[AES256_GCM,data:w2Dz8JfsPL117QafGqfaegFxZWfxp86WzLq0nD7e6Y5dhbf94/+MDeAZgenltujJIwk/B5btglXD+0ba2yExhsXC4o81WJchY8Bs4nMAsic1PXtIIzgHLVCwF0iTJqc0+zwuUlDP0jLNcjpSPXoYsacTXkokWccvfPixNW7ofaQ=,iv:pwo2Y9U8jbz+vppBrxnFJMFRHAZfwoR+bYsUNhse4Fk=,tag:QPTz8xmQqIxHsVkxEcH0ag==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
