# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Zav/sYk4dpnlR+kxXRXGFi0LlYIzRs/W4Iqn17CLLV/xmfftZtwWJQ==,iv:7G/5ttXr2iywcy5fLRyzJysKRddPwM8emwcKfO0mzNc=,tag:DMaq/CCQSiHW9I3l1JiXMQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dzpk0zfneupvk2a8d0wu6n8n3deqkl2r7lpd7t3ln028zfcrqpgqv80w9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaEJGQTRsYUc1RE95VTM1
        cm9CbUdFL04raStPWGhCazNoMVJGdkYzVndnCjdhSENzNU9WUDl2MERybTVxY1BB
        R0pNT05oa3N1cmRjUDEyVmVaZXZZUzQKLS0tIFBzL0Fhdm4yZDRBVEJHbUM4dGRy
        NkpZVWkxK2JJN3RGcW1YWmp6Y1JicnMKau6sxr7vCEz+tL/7hWW6K/97nIXKJ4yZ
        PUq8FHnc9zFL3Y48oBMX1Yf3LtjwvCFJw6EvC+TYm6mqsv4SwCSQ6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-02T18:36:36Z"
  mac: ENC[AES256_GCM,data:B8iRAsqJnUooxgDAPhbTVUwazAUV+zaj9vP74Ka+YZxhtDjFJBuAUo9WInBpdXI4trmrmiYJJaG/odnf1md6r787Hkg41/eUka1vl1kLIzxxF6+fDWyH60If34rYGWxTMQdSJ9Z0fd1vT05cQKrFH8yvglY7te/8oai0j855aNs=,iv:7wiVsN24lVfPdvW9T8wyahcEpJu4z0yU9SZm9hDXAzE=,tag:YnLZ9cotQONTy+7Sm+72LA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
