crds:
  install: true
global:
  domain: argo.jw2.org
configs:
  params:
    server.insecure: true
  cm:
    statusbadge.enabled: true
    kustomize.buildOptions: --enable-alpha-plugins --enable-exec
    helm.valuesFileSchemes: secrets+gpg-import, secrets+gpg-import-kubernetes, secrets+age-import, secrets+age-import-kubernetes, secrets, secrets+literal, https
    resource.exclusions: |
      - apiGroups:
          - cilium.io
        kinds:
          - CiliumIdentity
        clusters:
          - "*"
  secret:
    argocdServerAdminPassword: $2a$10$YYhbEBBTN1Hs8MO967BjteoPXf4UYyNa23W/ixxO6Xo/iLkyL9Xm6
    argocdServerAdminPasswordMtime: 2025-02-17T23:26:52
    githubSecret: 7ac247ae96e1c1202359ef7b10899e95
controller:
  replicas: 2
  metrics:
    enabled: true
    applicationLabels:
      enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
dex:
  replicas: 2
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
redis:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
server:
  replicas: 2
  allowAnyNamespace: true
  ingress:
    enabled: true
    ingressClassName: internal
    annotations:
      external-dns.alpha.kubernetes.io/target: internal.jw2.org
    hostname: argo.jw2.org
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
notifications:
  replicas: 2
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
repoServer:
  replicas: 2
  serviceAccount:
    create: true
    name: argocd-repo-server
  rbac:
    - apiGroups:
        - ""
      resources:
        - secrets
      verbs:
        - get
  env:
    - name: HELM_PLUGINS
      value: /custom-tools/helm-plugins/
    - name: HELM_SECRETS_CURL_PATH
      value: /custom-tools/curl
    - name: HELM_SECRETS_SOPS_PATH
      value: /custom-tools/sops
    - name: HELM_SECRETS_VALS_PATH
      value: /custom-tools/vals
    - name: HELM_SECRETS_KUBECTL_PATH
      value: /custom-tools/kubectl
    - name: HELM_SECRETS_BACKEND
      value: sops
    # https://github.com/jkroepke/helm-secrets/wiki/Security-in-shared-environments
    - name: HELM_SECRETS_VALUES_ALLOW_SYMLINKS
      value: "false"
    - name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
      value: "true"
    - name: HELM_SECRETS_VALUES_ALLOW_PATH_TRAVERSAL
      value: "false"
    - name: HELM_SECRETS_WRAPPER_ENABLED
      value: "true"
    - name: HELM_SECRETS_DECRYPT_SECRETS_IN_TMP_DIR
      value: "true"
    - name: HELM_SECRETS_HELM_PATH
      value: /usr/local/bin/helm
    # For age
    - name: SOPS_AGE_KEY_FILE
      value: /helm-secrets-private-keys/key.txt
  volumes:
    - name: custom-tools
      emptyDir: {}
    # kubectl create secret generic helm-secrets-private-keys --from-file=key.asc=assets/gpg/private2.gpg
    - name: helm-secrets-private-keys
      secret:
        secretName: helm-secrets-private-keys
  volumeMounts:
    - mountPath: /custom-tools
      name: custom-tools
    - mountPath: /usr/local/sbin/helm
      subPath: helm
      name: custom-tools
    - mountPath: /usr/local/bin/kustomize
      name: custom-tools
      subPath: kustomize
    - mountPath: /usr/local/bin/ksops
      name: custom-tools
      subPath: ksops
    - mountPath: /helm-secrets-private-keys/
      name: helm-secrets-private-keys
  initContainers:
    - name: gitops-tools
      image: ajaykumar4/gitops-tools:1.0.1
      imagePullPolicy: Always
      command:
        - sh
        - -ec
      args:
        - |
          mkdir -p /custom-tools/
          cp -rf /gitops-tools/* /custom-tools
          chmod +x /custom-tools/*
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dzpk0zfneupvk2a8d0wu6n8n3deqkl2r7lpd7t3ln028zfcrqpgqv80w9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUGhSNndwVUFYNDhmbDNw
        a2xoaW9CMjhQcHNCRUd5S0ZVRmJuRDM0WmhNCklBVUc1VkNocnhJdTl2dFFmbWNz
        OXV5MVN1UVo5c2pHVWhaSnQybGV6MDAKLS0tIGRSZkpJY0JCM1g2akRFL2NPaXhI
        SE5wOWl6NjZKOWNrQy9SZzB6V25hSnMKGAmsfAhFIA/S5JiarH/7uI0v3m1fmoR/
        EQQCdNpucwJqwmbVYj3NUAnVdeXh5pwsasp3Dw9phy2ydBBmAzWD0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T04:26:52Z"
  mac: ENC[AES256_GCM,data:0PLQ21Bhi3xRwUtb9kjn7zwX72Ez2blK88OGe8jsG9fJ+lZ2nlyK1/Afm+RZ8bDQeEd3SssvozPdeVWfsVGnempbmsS1n8dLxhGUTHdr6dlNE+XrhWfBUOsEFYOjAvT0jhPI390OH1hjHWgvz5F56XXASyWQimiDU8lVEqFCR/c=,iv:NTTHGIgMYPddcN37cWFOQyVQkHOluf5Od9brT1/h8Fk=,tag:jWHfy4HvENssbnmpl7hv8g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
