apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: three14creations-com-production
spec:
  secretName: three14creations-com-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: three14creations.com
  dnsNames:
    - three14creations.com
    - '*.three14creations.com'
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dzpk0zfneupvk2a8d0wu6n8n3deqkl2r7lpd7t3ln028zfcrqpgqv80w9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxc1VIby9hLzVxaU15SGtl
        eXNUNHRGUWFhVHZkdkJCUFV2WmMxTm9yUEhjCitjL1RuRGJaeGtVNzJ5cmQ3dEZl
        bXVYZVo4MzJZTmJvSjVRSWVscnFuLzgKLS0tIExYRU9VV0ZyL1hYdXFLZXZNbXVH
        NFpjMlJUZUtwcTU2T3BDd0toL2VkTnMKEgMPPaA+rRRNs/tXalXqIDchCyOtTk9k
        gYUVFO6jFrwR+Vu/U0Kb3G9cZ6NuuEJOfyM5TkJbWZT7D8FsaBe03Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T05:01:00Z"
  mac: ENC[AES256_GCM,data:WhXDaiwBnQiFgTlYOH/TzG1BGrig5LKe/1PEicqCpQNmubTfjN4v5z1tlbO1W7aem4DJrOlRZ0PnQSTnDovNcCDiIkGlrip0Nty8Wi9JEtXAvCtEuHp9M6INsYVIuo0++V7aTSEDErhyw7UZN1XR33QmNViIhjnkLuFO9w8pMMM=,iv:IsmNWMogkmQI8mPwbKUWhPk4Cb8kpf7F9CNktJB4ytU=,tag:Dzzb/8WKPk1+bhT9VbKflQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
