apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jw2-org-production
spec:
  secretName: jw2-org-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: jw2.org
  dnsNames:
    - jw2.org
    - '*.jw2.org'
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dzpk0zfneupvk2a8d0wu6n8n3deqkl2r7lpd7t3ln028zfcrqpgqv80w9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQkZ3S2p0SGk3MkFTMjhU
        aWFxN204QUVJMnNWQURCZWpoV1l2WjBpVFcwCmFCL0FBZUE3OFpQYkZnU2k1WHF0
        NXJDQnBhZ2lBRWJSOEVQcDdqWmdpWEkKLS0tIGZscGFPUmFPUXNWWjNPaUtNNXF3
        SmJ2TkJ5SjRrTThwK1dXOFM3S0FRem8K9r6CLi4D+pab566g7cx5li6v4HiC4fcQ
        qZfSQzONRnxdnp7IUwJpzSklNaSInhGiQxiO2MMNGx94imxcmcBcJA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-02T18:36:37Z"
  mac: ENC[AES256_GCM,data:1N4y/HBATXc0i/0HzNTFbEpZkCPlZeT02o45xKys1d1ZDqAyzSd0hRnz4a8MMplNOniBMmXyNLBCUrsikJ2D9EI6FSPdY8WDP8Jqfr7dsnprEVPh9n7Tky5/Rcxh1fN+hbAxy4jxz8r1y619IC3XWpBgfEvtRdsH2oNOyHRo/w4=,iv:C3mNem7E6i48mQn4SxkaQI7LQvEDuofMnhXULIxatgc=,tag:COkLhlsLJis6V1tbKy3XFQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
