apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jw2-org-production
spec:
  secretName: jw2-org-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: jw2.org
  dnsNames:
    - jw2.org
    - '*.jw2.org'
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dzpk0zfneupvk2a8d0wu6n8n3deqkl2r7lpd7t3ln028zfcrqpgqv80w9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWGJVQkJHNk1aYUdCVVgv
        eTRBSVArdUYzaHVlakJwaWN2TzE5bnNFVEI0CmJ0QWw0Nk9ibFNVMkhMdkpIbFlD
        UWxYbjY5bGJnNGJaWWZBZXJUOWJoMVUKLS0tIG1iS2ZDVTNTbGpmWWY0Vm4yN3la
        UHcrVzJkT1diNzJFYldJdElEUzdKL2sKEgJu0yDELddRY0MsaTEWwFP2AszzuCaF
        CeRRHZ7bXNSuyUq1OqFDgNLfHf3K4dqMKCx0DVNnazRn4EcGhIDr6A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T04:26:52Z"
  mac: ENC[AES256_GCM,data:vA5QvBn00N14Asji9ckKetZI8RFcdnnwZNxUjBCDejfIqpSms7G76vwhGLr5HcOxVVgUld0espPRWA418ls89WvFOFJN/M6gxTUquV3DpbrFB6qqFrYIH1mDTD2WbS8b57tJfFBNiEfPKWsQUl66AWOihQ3lNDWaMp6ZSlT7+X0=,iv:2aFiC0dRBfPOCtvxtNXwzKaedXBpiOG0jh606khPeEo=,tag:eFOmmGEKM8evwl5a49HoaA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
