apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: three14creations-com-staging
spec:
  secretName: three14creations-com-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: three14creations.com
  dnsNames:
    - three14creations.com
    - '*.three14creations.com'
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dzpk0zfneupvk2a8d0wu6n8n3deqkl2r7lpd7t3ln028zfcrqpgqv80w9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QTUvV3d5YWM4WE1LT1lK
        K2hxV2NSVGdlQWY5NTdhSFVoNWZJazF0Vnk4ClkyVVpLQ1BkNHgwQWVLMjNLLzBV
        VmdKWnp4S2RxczZyZ09KUit0Zk9aZFUKLS0tIG5FUGM4QWJrMUpDVi8xOG1HdCtC
        TllFZVAvc2hCdGpWS2xpb0pPL29hblkK9o9U/UbY1bNmCnZ1FMup8lffYw3Mjm2h
        kmoubuMszasy1PDz62yk3SMQ1qomN/aI5N7Mm5cmb27T2CqiHK6hew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T05:01:00Z"
  mac: ENC[AES256_GCM,data:MHiEauDqWemK9JVKhWCOGyU4eJdxNn+lxnEDXJ/uh2L+s2E8bnv36zp+1X2XAqSKkZrrwvoNoJNzPIOCYnXMN7xConsOmC3AzwlgacHxeUUOiohVntTpADyidHv6kMGyn3WdGtCuQZij7458u4ABY0zbrFHy09dynju5FXwVOoI=,iv:u9nDvqeYq/vePTprMFHO5towJKDsbJA33taTZB1Q22c=,tag:QBp+TsQ3ACATSQFlieaL4w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
