apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jw2-org-staging
spec:
  secretName: jw2-org-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: jw2.org
  dnsNames:
    - jw2.org
    - '*.jw2.org'
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dzpk0zfneupvk2a8d0wu6n8n3deqkl2r7lpd7t3ln028zfcrqpgqv80w9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QTNlQUh2N0RQdG5qWjdz
        a1gzcXlsZXMxSmhUTk9TUldnN2xLSzArOXlFCk9iV2Y3alVIb0dYeTB5aytpbUZz
        bTNVWEZWNjcxSFJUTzhIcXVEZlpxdkEKLS0tIDdKOC9xS3VIZkM0QzJNMVNRNEpY
        Qm1OMTF5aUdZQ1B4SHFKQ084dW1DclUKxYWrqeGfWkrjRbB7Adw/VVibPR9bdznB
        ij/HkbVOyHMQvW64xZV6i38sD+WXhJXSdVOXCW/qTvdPMVHt96qPAA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-02T18:36:37Z"
  mac: ENC[AES256_GCM,data:wvnxtgcemLX4MjBFsh8f2pcr4V96abYT/pTjUk4KpDm+IacJ5bHERc6OkUmiWeXMtqe1ONkPSPiJMlDblehcLb/alOL4Ey0qPoG+a121EwAt1Y89NM+DAusyt7sHotrXH6IhZ6TlIMAHt6rNBJycPlpUh/fVsQVpD7CRtfvfI1I=,iv:0PktIYC15ihoJ79sFOVNleouwnTAg928draL73jlJc8=,tag:ujHxgYIBOyUEWeJWIkVQEQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
