apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jw2-org-staging
spec:
  secretName: jw2-org-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: jw2.org
  dnsNames:
    - jw2.org
    - '*.jw2.org'
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dzpk0zfneupvk2a8d0wu6n8n3deqkl2r7lpd7t3ln028zfcrqpgqv80w9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDcW8rWFlncWdmajFJZGZl
        dURtSDhwU1YzMlJsNElZK0YvTkJGVExiNTBBCmxTTHJ3QzFlbmZFRDVIOUg0bnJQ
        Rkd2WVFiekVpcGQ3TUs5N2krcTlNbUUKLS0tIEZLTFlFNnJSbkQzSDFkUmVxVUtM
        M2Fab2g1WjcwY0h4b0kvcS9JbEFoODgKwLqHVn6pAXc5pKNisSJ8wJzR7hN3fwde
        vT2Bjq+hUSJvNuBZy8YiTRR+RDij2SnSyowvpNnrGZ2uOUSe4xe3jw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T04:26:52Z"
  mac: ENC[AES256_GCM,data:zZ/QE/0JOmW844oe0XA9FddY96+4f1HthpUJq8ATl75a13WU2s+f5MdJFfBbrGx0ERBKzgSpak2sSBGjBJ8r3MwE6wyGFJclNe/H2dU9RwmmOW4Ngq+YNl4AQ1A2O4R2WseswmeHFYR6FbLSoJIl+mJyNBI+TCXPh4Wn9oLKs1A=,iv:dT35KA5BR9sRzWi5PvmOfdX2hjX7h0LlZas3WscWgDE=,tag:scpxa8/3x0d1e1338PdY1A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
