controllers:
  echo-server:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 34
        env:
          HTTP_PORT: 8080
          LOG_WITHOUT_NEWLINE: true
          LOG_IGNORE_PATH: /healthz
          PROMETHEUS_ENABLED: true
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 64Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    seccompProfile:
      type: RuntimeDefault
service:
  app:
    controller: echo-server
    ports:
      http:
        port: 8080
serviceMonitor:
  app:
    serviceName: echo-server
    endpoints:
      - port: http
        scheme: http
        path: /metrics
        interval: 1m
        scrapeTimeout: 10s
ingress:
  app:
    className: external
    annotations:
      external-dns.alpha.kubernetes.io/target: external-int.jw2.org
    hosts:
      - host: '{{ .Release.Name }}.jw2.org'
        paths:
          - path: /
            service:
              identifier: app
              port: http
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dzpk0zfneupvk2a8d0wu6n8n3deqkl2r7lpd7t3ln028zfcrqpgqv80w9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRmpyK0hIb21PcGY2UHFC
        Y2ZJa2lJcmVNOUxBa1NpR1hwaWpwRWhUSXhnClJDY0ZyQkRqZG5kTjVBTFBtdEhB
        Ylp4NXhSdzJtR3VvdTBlWkZ5KzUrV1UKLS0tIGcyQkpuWDFwVE84cTdoVVVqRlpr
        bFlJWTNCOXlkbDB0bnVMdnZzTjNzNzAKusC5M1gN4ifpq1POyhk1gV8gCEK/CVc+
        EVBVjyAXKB64Pug+QN/ackoQJWZKSBShWiYHRtE86m90Ovno8L2qNw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T04:26:52Z"
  mac: ENC[AES256_GCM,data:dqIUJyEfqenX3nVwzaIs0xMavSiz+RcaoHxeQ+m+xlveUKgTxJlZyVxjsdkhuzabgtVGPtX8yCp+SKrwlM3s0s7LHdRF4MPw/kVPsrIuL4/BHh8okO8C7a22raCXogG7yWc4fUHv3DGa4oq77BnU23qAxRrIPs3gY8u6KZIv0o0=,iv:y4IoCYWlnJwn1mt74MemOSJE+2n5uwpgFKKnYyUHmFE=,tag:Sz9QuTKJjD31yNH/5cYeQg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
