apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared
spec:
  endpoints:
    - dnsName: external-int.three14creations.com
      recordType: CNAME
      targets:
        - 17bfc0e9-c204-4888-a3fb-746a29e80d2b.cfargotunnel.com
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dzpk0zfneupvk2a8d0wu6n8n3deqkl2r7lpd7t3ln028zfcrqpgqv80w9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQThkYTdTU2VZYVhKWGJJ
        eHhXbDR4WUN6cXZuWFNsUzQvSzRGLzcrTDBNCllqSUwwcHRsN2N1SHJxczV6TTYw
        dklkL3huK1dQWm1PMkFrVDdyck1OYzAKLS0tIGtETDNieTNySDNhWWhzd05pWlBL
        ZFUzbXhwR0swZ2JHbWVhMjFlOW1iRWsKzOZP6EGfx9N3Jf1N1oXGCqjKCKGDfQet
        wTU+Gg4Yecm7allcoZ0t1d6Le3klX+Jq3ZQP9wWuSl9RaEWAd6v1Lg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T05:00:59Z"
  mac: ENC[AES256_GCM,data:Vdnxk6Tx27a78dpxfQHVZIEOF4S0ZE+dHuVGEs1mHxXH89RdQQYSXg0aeWvcgTJrgb/K3LZqNO0Q6WEu78uCwr8kjDEsA8so4e0A7/Dc2mVO2FoFgGBhKZxaEn4DWP0CprcNzREjTF07S1rxEFjFnDgOR4oTIxzygtmiNTiiqjk=,iv:PvKZbl1n/PCTVfyO0B1xxH0TeLqHxvGuo87l/xPEKWQ=,tag:ov/P7LhhlskfYl2m/oy4kQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
