apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared
spec:
  endpoints:
    - dnsName: external.jw2.org
      recordType: CNAME
      targets:
        - 42a42d5a-003b-4dd2-9c57-bf7a65072be1.cfargotunnel.com
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dzpk0zfneupvk2a8d0wu6n8n3deqkl2r7lpd7t3ln028zfcrqpgqv80w9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENmJqQjhxY3V0cXZmNDhX
        MXlOMFljRDBSWER1c2lxWlh1eTRLbVRQTVNNClNwVk1aYStmRTNOS3NDZGFjV0Vz
        WTNrZFgyeXMveHhhWDcwNUM1R1YxUUkKLS0tIDh2ZG8rOXBHMGVQL21JL2ZaK0lx
        V05ZWUhYTk1ndzZHaUhUN29jYk8zRGcKLIEnoiqwh1a2AL81s+htOzD5eYVJ+G/X
        QC/4w0FeOqTnXo0vCC+hCEDQBK87mZhXb+IwXFqmOk1LZW44uH4mOA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-02T18:36:36Z"
  mac: ENC[AES256_GCM,data:VN3XiG1lRug7IgbvKLMoR4ZF5KSNBnkG+sNIm8yZp3Foqdsh0Nvokg0HtSuobVKzXKCt98WaQmOsf01jwMJR5LbKodl9HzbCb3khn9blrBMMtwBaSfrLHikmofzNXf+dJm54pYpg2fWiWeDzUiRncTfKUzPlMwheX7mulg3IBSk=,iv:/kWrw4uK0JTGTAdIL9ZpX9Y+VGwrGhNtrpLtGpnuOok=,tag:85HSay2l2iGTRubAbH9UEg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
