fullnameOverride: k8s-gateway
domain: jw2.org
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    io.cilium/lb-ipam-ips: 172.16.0.85
  externalTrafficPolicy: Cluster
watchedResources:
  - Ingress
  - Service
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dzpk0zfneupvk2a8d0wu6n8n3deqkl2r7lpd7t3ln028zfcrqpgqv80w9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTlJjeWRaakQvL2tkWlIz
        bDh0eFJuV1BpK1Bxa25mZXZLMlA0ajFVN1FzCnFxZklKY1pHamhhVU9RTDdQZXQr
        MFVzZGMxRVZxdFJST3BPb3pHM05hVVkKLS0tIHhZRWFBVnVRR1IvZnZaVXFSSE51
        N2VRWU44R1ZjQm9HbVZIRU95WGJVMW8K6mv8HaC6NgmNwujcTk3T3BFo9p8CX+vw
        vu/5G2ehh0nHyEanQuNYnisqffS1ev1jgV3qc6rN414qjb8GliNukQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-02T18:36:37Z"
  mac: ENC[AES256_GCM,data:RJSvJwmGUxTAx+5rmXcPo+8KdAGecXN+J5QAYXm9FNJ7+daqZD/vgW7Zd3xElC2pHrJBtEKClMqFAb+RXU/ysKs/pPupq4Yg8/w1kUI7XYBIT1s+GWBtSY6T9Gu8HsJXxNAWCmM/MblH7Pe3gJExU4lmE385pjfed75whmUQiBU=,iv:QGbeNp9MMjfew46pOIoWIrYjHlbUiw7/3lMim+yjEJw=,tag:BmK1/KbecxwpY47ydOSzLQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
