fullnameOverride: k8s-gateway
domain: jw2.org
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    io.cilium/lb-ipam-ips: 172.16.0.85
  externalTrafficPolicy: Cluster
watchedResources:
  - Ingress
  - Service
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1dzpk0zfneupvk2a8d0wu6n8n3deqkl2r7lpd7t3ln028zfcrqpgqv80w9d
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTjdORzM0ME5hM3VCQis5
        b25aeUt1Zlh0eHd2S3I0bTdUazR3Wkg0dFhvCkZZL1dpbTZ6TmhVa0F5K1ZWcGJt
        M3lqR3k1WFRoQ3h3MnFhTkt6bnBRWXMKLS0tIEdhMy8xWW8vL0Q0TVhjUnoyMVAx
        ZFd6OEF4Mk5SSW5ub2VPbVJTa0Q4L2MKtkkETbJv/Kh70xwldxV5sExFeawpi7QE
        Z2R1Yhkh8OMdZJeQCsewrraOWwrjkfegk2WqJpQIj14Pq5k9kIPc9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-18T04:26:53Z"
  mac: ENC[AES256_GCM,data:GulmDHbvyoBSaMj4o6ABK7Me5Ra3niGiYfnUK1drkZrACb1YdEPeIFtn6AwoGt/7NzABGeMmEly/FSwCaHkayE4gCEFeZpHhxT3/OqbJw/FWqwXAw5npwmjvrZRrprDx8egjZRGEXVxzTRKHBI4jHp9mLeUZpjQT7gpiCrT3Xos=,iv:7odg3572wksgwf3qJpB8lYzuhbxvrN8iJOiJ11xZqnA=,tag:HIV2EfQGpsrOZKj+zXexiQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
